services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
      - PORT=3000
    volumes:
      - ./tmp:/app/tmp
    restart: unless-stopped
