services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      # Se puede definir en un fichero .env o exportar en la shell antes de docker-compose
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./tmp:/app/tmp
    restart: unless-stopped
